### ISSUE TITLE
Updated Errors

### ISSUE THREAD

**Issue by zhouxp9709** [VIB-PSB/ksrates#57] opened 2024-03-28 11:41 UTC
Hello!
I am unable to update ksrates-1.1.3 to ksrates-1.1.4 with the following command:
```
pip3 uninstall ksrates
git clone https://github.com/VIB-PSB/ksrates
cd ksrates
pip3 install .
```
The update looks like the following:
```
liu@admin1 14:08:06 /vol2/software/ksrates-1.1.4
$ /vol2/software/Python-3.7.12/bin/pip3 install .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /vol2/software/ksrates-1.1.4
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: click==8.0.1 in /vol2/software/Python-3.7.12/lib/python3.7/site-packages (from ksrates==1.1.3) (8.0.1)
Requirement already satisfied: numpy==1.21.2 in /public/home/liu/.local/lib/python3.7/site-packages (from ksrates==1.1.3) (1.21.2)
Requirement already satisfied: scipy==1.7.1 in /public/home/liu/.local/lib/python3.7/site-packages (from ksrates==1.1.3) (1.7.1)
Requirement already satisfied: click==8.0.1 in /vol2/software/Python-3.7.12/lib/python3.7/site-packages (from ksrates==1.1.3) (8.0.1)
Requirement already satisfied: numpy==1.21.2 in /public/home/liu/.local/lib/python3.7/site-packages (from ksrates==1.1.3) (1.21.2)
......
Successfully built ksrates
Installing collected packages: ksrates
  Attempting uninstall: ksrates
    Found existing installation: ksrates 1.1.3
    Uninstalling ksrates-1.1.3:
      Successfully uninstalled ksrates-1.1.3
Successfully installed ksrates-1.1.3
```

Thank you!
Xuping

**Comment by Cecilia-Sensalari** [comment] 2024-03-28 13:08
Hi zhouxp9709 :)

I'm not sure what the problem is, and right now I can't install it myself to check it out, but here is a possible cause: the latest release is called 1.1.4, but the associated `__version__` [file](https://github.com/VIB-PSB/ksrates/blob/v1.1.4/ksrates/_version.py) was not updated accordingly, so it still contains "1.1.3" (my bad).
Can it be that the installation procedure correctly installs the new version but writes on screen "ksrates-1.1.3" because it reads from `__version__`? You could check whether the ksrates directory you have cloned contains the new code, for example the lines related to a recent [bugfix](https://github.com/VIB-PSB/ksrates/commit/27b0ea90404bed5f355a52892082e64cf15ced26).

Best,
Cecilia

**Comment by zhouxp9709** [comment] 2024-03-28 13:17
Hi Cecilia

It should be that ksrates-1.1.4 was not successfully installed, because the error about i-ADHoRe still exists: 
```
ERROR i-ADHoRe execution failed with standard error output:
Warning: Dubious indirect gene relationship between GENE1 and GENE2, closest genes get same color in alignment
ERROR Exiting.
```
Best,
Xuping

**Comment by Cecilia-Sensalari** [comment] 2024-03-29 08:43
Hi zhouxp9709,

Perhaps it depends on how you are running ksrates. Here are a couple of questions: are you using Nextflow? Are you using a container? Is there something cached that might be indirectly reused?
In any case, since I've changed the version number in the` __version__` file, could you try again by recloning the master branch (not the release 1.1.4 tag)?
Cheers!

**Comment by zhouxp9709** [comment] 2024-03-29 09:32
Hi Cecilia

I installed it manually. By recloning the master branch, I managed to install ksrates-1.1.4, but the error about i-ADHoRe is still there:

```
ERROR	i-ADHoRe execution failed with standard error output:
[node4:86542] mca_base_component_repository_open: unable to open mca_oob_ud: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
[node4:86541] mca_base_component_repository_open: unable to open mca_oob_ud: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
[node4:86541] mca_base_component_repository_open: unable to open mca_btl_openib: libosmcomp.so.3: cannot open shared object file: No such file or directory (ignored)
[node4:86541] mca_base_component_repository_open: unable to open mca_btl_usnic: libfabric.so.1: cannot open shared object file: No such file or directory (ignored)
[node4:86541] mca_base_component_repository_open: unable to open mca_mtl_psm2: libpsm2.so.2: cannot open shared object file: No such file or directory (ignored)
[node4:86541] mca_base_component_repository_open: unable to open mca_mtl_ofi: libfabric.so.1: cannot open shared object file: No such file or directory (ignored)
[node4:86541] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
.................
ERROR Exiting.
```
Cheers!

**Comment by Cecilia-Sensalari** [comment] 2024-03-29 09:57
The recent [bugfix](https://github.com/VIB-PSB/ksrates/pull/46) I talked about before avoids that i-ADHoRe error messages starting with "Warning" are treated as fatal errors (like the `Warning: Dubious indirect...` above). However, the error lines you are showing now are something else: I didn't find any hint of the this error text within i-ADHoRe code itself, so I looked up online.
I found by copy-pasting the line that it could be related to OpenMPI, which is used when asking for parallelization through `--n-threads`. Can this be of any help for finding a solution?

**Comment by zhouxp9709** [comment] 2024-03-29 11:50
This problem was solved by updating openmpi to the latest version.

Thank you!

**Comment by zhouxp9709** [comment] 2024-03-29 12:03
Is it possible to execute BLASTP using diamond? blast+ is too slow.

**Comment by Cecilia-Sensalari** [comment] 2024-03-29 12:35
Unfortunately at the moment it's not possible, as the command to run blastp is [hardcoded](https://github.com/VIB-PSB/ksrates/blob/master/ksrates/fc_wgd.py#L499).
The following is a workaround: before generating the blast table (called `myspecies.blast.tsv`), the code checks if the file already exists at `paralog_distributions/wgd_myspecies/myspecies.blast.tsv`; if you first run diamond yourself and then move its output to such default location and the expected filename, the code will find it, skip the blast run and use your diamond table.

**Comment by zhouxp9709** [comment] 2024-03-30 03:43
I get it. I don't have any more questions.

Thank you!

**Comment by Cecilia-Sensalari** [comment] 2024-04-01 07:16
Since this issue is solved, I'm going to close it!

**Closed by Cecilia-Sensalari** 2024-04-01 07:16 UTC
